### ISSUE TITLE
Implicit Sparse Identification Example in Docs is broken

### ISSUE THREAD

**Issue by AlCap23** [SciML/DataDrivenDiffEq.jl#130]
The example of the [Michaelis-Menten Kinetics](https://datadriven.sciml.ai/dev/sparse_identification/isindy/) is currently not working.

All other tests and examples are running though. Needs investigation.

**Comment by AlCap23** [comment]
Alright. Needed to adapt the scalarization algorithm. This here seems to work.

```julia

function michaelis_menten(u, p, t)
    [0.6 - 1.5u[1]/(0.3+u[1])]
end

u0 = [0.5]
tspan = (0.0, 4.0)
problem = ODEProblem(michaelis_menten, u0, tspan)
solution = solve(problem, Tsit5(), saveat = 0.1)
plot(solution) # hide

X = solution[:,:] #+ 1e-4*randn(size(X)...)
DX = similar(X)
for (i, xi) in enumerate(eachcol(X))
    DX[:, i] = michaelis_menten(xi, [], 0.0)
end

@variables u
basis= Basis([u^i for i in 0:4], [u])

opt = ADM(1e-1)
f_target = WeightedSum([0.0 1.0], x->identity(x))
Ψ = ISInDy(X, DX, basis, opt = opt, maxiter = 1000, rtol = 0.9, alg = f_target)
print_equations(Ψ, show_parameter = true)
parameters(Ψ)

sys = ODESystem(Ψ)
dudt = ODEFunction(sys)
ps = parameters(Ψ)

# Simulate
estimator = ODEProblem(dudt, u0, tspan, ps)
sol_ = solve(estimator, Tsit5(), saveat = 0.1)

plot(solution.t[:], solution[:,:]', color = :red, label = nothing)
plot!(sol_.t, sol_[:, :]', color = :green, label = "Estimation")

```

**Comment by AlCap23** [comment]
#131

**Comment by AlCap23** [comment]
Working locally but not right in the docs.

**Comment by AlCap23** [comment]
Most likely fixed with #132, but no build since `NameResolution` throws errors ( I suspect [this issue](https://github.com/thautwarm/NameResolution.jl/issues/3))

**Comment by AlCap23** [comment]
Okay, this is strange. Locally, the tests run fine, find the right equation and spit out a good approximation.
On Travis, these fail. I am slightly concerned with this. Maybe we switch back to the former implementation, which is a little more expensive in terms of storing but otherwise should be fine.

@ChrisRackauckas Any thoughts on this?

And for reference the local results.

![image](https://user-images.githubusercontent.com/20998300/88931726-7ee67980-d27d-11ea-8ca1-aebbc124172f.png)

![image](https://user-images.githubusercontent.com/20998300/88931810-9aea1b00-d27d-11ea-9b45-7355ed85947b.png)

**Comment by ChrisRackauckas** [comment]
What should I run?

**Comment by AlCap23** [comment]
It's `test\isindy.jl` which should give you the info print.
