### ISSUE TITLE
Store the low-rank factorization of the Koopman operator for memory saving?

### ISSUE THREAD

**Issue by loiseaujc** [SciML/DataDrivenDiffEq.jl#135]
Hi guys,

I have been working with DMD and its different flavors for the past ten years or so now, primarily with Python, and start to move on to Julia.

As far as I understand the source code, it seems to me that you are currently storing the whole n x n DMD approximation of the Koopman  operator once fitted. Note that this may be quite inconvenient if one applies such analysis to high-dimensional systems (e.g. fluid dynamics in my case). Explicitly storing this potentially extremely large may put a heavy burden on the memory.

Since the whole point of DMD-like techniques is to obtain a low-rank approximation of this Koopman operator, wouldn't it be better to store it in a factorized way, i.e. store only the low-rank bases for the input and output spaces as well as the corresponding eigenvalues (or r x r matrix representing the projection of the Koopman operator onto these bases) and redefine the multiplication to make use of this factorization ? I believe it would require only relatively little modifications to the current code and might enable the use of this package to effectively analyze much larger systems.

**Comment by ChrisRackauckas** [comment]
That makes a lot of sense, and yes it shouldn't be a big change to make all of the DMD tooling store the low-rank operator.

**Comment by AlCap23** [comment]
Hey @loiseaujc ! Sorry for the long absence w.r.t. this topic. I've rewritten the overall setup in such a way that `DMDSVD` now computes the reduced eigendecomposition ( see [here](https://github.com/SciML/DataDrivenDiffEq.jl/blob/8f74b08fea1b8c8c16f733e7667bb73bb0ba1e24/src/koopman/algorithms.jl#L95) and below ). Additionally, if you're just interested in the operator and not a system, you can just get the matrices of the estimation. Would this be sufficient?

**Comment by loiseaujc** [comment]
Awesome! I've been side-tracked by other projects but should return to DMD very shortly so timing is perfect actually :)
