### ISSUE TITLE
DataDrivenDiffEq does only train along one trajectory

### ISSUE THREAD

**Issue by freemin7** [SciML/DataDrivenDiffEq.jl#136]
> I am i seeing it correctly DataDrivenDiffEq only supports building Koopmann operators along one trajectory at a time?
> (In non-linear systems it might not be possible to capture all the dynamics with one initial condition)

> if i had to propose a change the Koopmann could be directly "trained" to match f(u,p,t) over some collection of u,p,t.

> that might could be achieved via an Optimal DMD.

**Comment by AlCap23** [comment]
So I have finally found some time to write a short tutorial ( see #157 ), which will be merged shortly.

Can you explain a little bit more what you meant by trained in the context ? Train an embedding, an operator or simply f(u,p,t) via a neural networks ? I think I misinterpreted it at the time.

**Comment by AlCap23** [comment]
Feel free to reopen if necessary ;)
