### ISSUE TITLE
Problem with the latest commit of DataDrivenDiffEq

### ISSUE THREAD

**Issue by finmod** [SciML/DataDrivenDiffEq.jl#143]
Just attempting to update, I get this error message that blocks all uses of SciML packages.

                _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.0 (2020-08-01)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.5) pkg> st
Status `C:\Users\Denis\.julia\environments\v1.5\Project.toml`
  [be33ccc6] CUDAnative v3.2.0
  [8f4d0f93] Conda v1.4.1
  [3a865a2d] CuArrays v2.2.2
  [2445eb08] DataDrivenDiffEq v0.3.3
  [39dd38d3] Dierckx v0.4.2
  [587475ba] Flux v0.10.4
  [56d4f2e9] Gridap v0.13.4
  [7073ff75] IJulia v1.21.3
  [961ee093] ModelingToolkit v3.17.0
  [8faf48c0] NeuralNetDiffEq v1.6.0
  [315f7962] NeuralPDE v2.0.0
  [1dea7af3] OrdinaryDiffEq v5.42.3
  [91a5bcdd] Plots v1.6.0
  [30cb0354] SciMLTutorials v0.8.0 `https://github.com/SciML/SciMLTutorials.jl#master`
  [789caeaf] StochasticDiffEq v6.25.0
  [44d3d7a6] Weave v0.10.3

(@v1.5) pkg> up
   Updating git-repo `https://github.com/SciML/SciMLTutorials.jl`
ERROR: Unsatisfiable requirements detected for package DataDrivenDiffEq [2445eb08]:
 DataDrivenDiffEq [2445eb08] log:
 ├─DataDrivenDiffEq [2445eb08] has no known versions!
 └─restricted to versions * by an explicit requirement — no versions left

(@v1.5) pkg>

**Comment by AlCap23** [comment]
I think this can be resolved by tomorrow. I am finishing up some minor PRs and up the deps before v0.4 . Most likely this will resolve the error. Thanks for pointing out!

**Comment by finmod** [comment]
Thank you your prompt clarification. I have a follow-up question for you: which Tex editor do you use for your contributions to the "Universal Differential Equations for SciML" paper?

**Comment by AlCap23** [comment]
Overleaf. I did use also VSCode for an earlier draft, but most of the time I use overleaf now.

**Comment by AlCap23** [comment]
I just registered the new version. 

https://github.com/JuliaRegistries/General/pull/20191

If anything comes up, let me know. Otherwise I'll keep this open until tomorrow and close it.

**Comment by finmod** [comment]
Perfect. Thank you.
