### ISSUE TITLE
Δt in DMD: Allow arbitrary time array?

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DataDrivenDiffEq.jl#15]
Would it be possible to instead allow for an array `t` of times for the observations? Having this be Δt seems restricting, and it's not clear to me this is required by the method.

**Comment by ChrisRackauckas** [comment]
Any why are the two dt defaults different?

**Comment by AlCap23** [comment]
No specific reason, maybe my degree of tiredness.

I don't know if an array of ts could be passed in. Right now we require the data to be sampled with a fixed dt to approximate the continuous representation. For varying dt this might break. I did a quick lookup but found no real source on this. In Tu et al. they just mention that the ordering does not matter and the data can be non sequential. We could throw in something like the mean diff over the time, but I will have a look at some examples first.

**Comment by AlCap23** [comment]
In [this paper](https://arxiv.org/pdf/1909.10638.pdf) the DMD algorithms are extended to be used on differential data. So if we pass in the differential states ( like in sindy ), we can do a sufficient approximation. 

Given the current structure of the `Koopman` , I would like to adapt this in the future. So in general more like a "classical" system with the operator, a mapping from state to observables, from observables to states and likewise to input. So more like the `A, B, C, D`  matrices from control.

**Comment by ChrisRackauckas** [comment]
What we really need to do here is use DataInterpolations.jl to get a spline to get a derivative estimate using unevenly spaced data, or use FiniteDifferences.jl. Something like that.

**Comment by AlCap23** [comment]
Resolve with #89
