### ISSUE TITLE
On automatic creation of Basis vector in SInDy

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/DataDrivenDiffEq.jl#153]
Hello,
It would be great if someone points me to any ideas on creating Basis vector in SInDy , say using polynomial terms of multiple variables of higher degrees in more efficient manner in Julia. For eg.
`Basis = [1, x, y, x^2, y^2, xy, x^3, y^3, xyz, y x^2  ,x y^2]`

This would be great tool and increase usability of SInDy, for eg.. pySINDY library at https://pysindy.readthedocs.io/en/latest/examples/3_original_paper.html#cubic-2d-ode
enables one to create features/basis simply by 
stating as follows

`import pysindy as ps
feature_library=ps.PolynomialLibrary(degree=poly_order)`

**Comment by ChrisRackauckas** [comment]
Do you mean dictionary learning methods like https://arxiv.org/pdf/1906.03959.pdf ? I had an issue going for this in https://github.com/SciML/DataDrivenDiffEq.jl/issues/34 . Indeed it would be a great thing to do.

**Comment by AlCap23** [comment]
I think this is more related to a wrapper for convenience :) . So given 2 states, create a basis of degree N with a simple call of

```julia
eqs = PolynomialBasis(states, degree = N)
```
which spits out  ```[1, x, x², ...., x^N, y, y², ....y^N, x*y, x²y, y²x,....]``` . Same goes for Fourier Basis with coefficients. 
So something similar to [Tensor Product Layer](https://github.com/SciML/DiffEqFlux.jl/blob/master/src/tensor_product_layer.jl) in DiffEqFlux. 

This would be awesome to have and I just did not have the time to tackle this tbh.

**Comment by yewalenikhil65** [comment]
I think this file should give an idea (unfortunately, i am not much familiar with pysindy library)

https://github.com/dynamicslab/pysindy/blob/master/pysindy/feature_library/polynomial_library.py
https://github.com/dynamicslab/pysindy/tree/master/pysindy/feature_library

**Comment by AlCap23** [comment]
This works for small sizes of variables and a small degree

```julia

function PolynomialBasis(x::Array{Operation}, degree::Int64 = 1)
    @assert degree > 0
    n_x = length(x)
    itr = Base.Iterators.product([0:degree for i in 1:n_x]...)
    _check_degree(x) = sum(x)<=degree ? true : false
    itr_ = Base.Iterators.filter(_check_degree, itr)
    coeffs = collect(itr_)
    n_c = length(coeffs)
    eqs = Array{Operation}(undef, n_c)

    @inbounds for i in 1:n_c
        eqs[i] = simplify(prod(x.^coeffs[i]))
    end
    eqs
end
```
But takes forever for a larger set of states / bigger degree.

**Comment by yewalenikhil65** [comment]
Hello,
This is a nice implementation. I don't think anyone might need these many combinations but its worth it to measure the performance.
I was wondering (since this looks more like a combinations problem), if we can use Julia package combinatorics to generate the multi-monial terms for the Basis:

Roughly speaking..
`julia> using Combinatorics

julia> collect(combinations(1:3,2))
3-element Array{Array{Int64,1},1}:
 [1, 2]
 [1, 3]
 [2, 3]`

where `combinations(a,n)` gives combinations of objects(here array), taking n at a time.
Sorry if this is not completely related to out issue.
