### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by AlCap23** [SciML/DataDrivenDiffEq.jl#176]
- [ ] UODE Example
- [ ] Extended UODE Example
- [ ] System conversion

**Comment by finmod** [comment]
I have a problem with the phasing-in of the new syntax in a recent paper by @ChrisRackauckas. The code to execute is:

Universal ODE Part 2

using DataDrivenDiffEq
using ModelingToolkit

Create a Basis
@variables u[1:2]

Lots of polynomials
polys = Any[]
for i ∈ 0:2, j ∈ 0:2
    push!(polys, u[1]^i * u[2]^j )
end

h = [unique(polys)...]
basis = Basis(h, u)

opt = STRRidge(3)
 
Create the thresholds which should be used in the search process
#thresholds = exp10.(-6:0.1:0)


for k in 1:300
    x_sol, y_sol, UDE_SGLD = UDE_term(UDE_SGLD, rand(1:300))
	Ψ = SINDy(ode_data[1:2, 1:end], UDE_SGLD[1:end], basis, opt = opt, maxiter = 10000, normalize = true, denoise = true)
    plot!(x_sol, y_sol,UDE_SGLD[1:end], alpha=0.04, color = :red, label = "")
end

aicc_store = zeros(1, 100)

for i in 1:100
x_sol, y_sol, UDE_SGLD = UDE_term(UDE_SGLD, i)
Ψ = SINDy(vcat(x_sol', y_sol'), UDE_SGLD[1:end], basis, opt = opt, maxiter = 1000, normalize = true, denoise = true) # Suceed
aicc_store[i] = Ψ.aicc[1]
end


x_sol, y_sol, UDE_SGLD = UDE_term(UDE_SGLD, findmin(aicc_store)[2][2])
Ψ = SINDy(vcat(x_sol', y_sol'), UDE_SGLD[1:end], basis, opt = opt, maxiter = 10000, normalize = true, denoise = true) # Suceed

The error is:

WARNING: using ModelingToolkit.parameters in module Main conflicts with an existing identifier.
MethodError: no method matching SINDy(::Array{Float64,2}, ::LinearAlgebra.Adjoint{Float64,Array{Float64,1}}, ::Basis, ::STRRidge{Float64}; opt=STRRidge{Int64}(3), maxiter=10000, normalize=true, denoise=true)
Closest candidates are:
  SINDy(::AbstractArray{S,2}, ::AbstractArray{S,2}, ::Basis, ::T; p, t, maxiter, denoise, normalize, convergence_error) where {T<:DataDrivenDiffEq.Optimize.AbstractOptimizer, S<:Number} at C:\Users\Denis\.julia\packages\DataDrivenDiffEq\kSbz2\src\sindy\sindy.jl:148 got unsupported keyword argument "opt"
  SINDy(!Matched::AbstractArray{S,1}, ::AbstractArray, ::Basis, ::T; kwargs...) where {T<:DataDrivenDiffEq.Optimize.AbstractOptimizer, S<:Number} at C:\Users\Denis\.julia\packages\DataDrivenDiffEq\kSbz2\src\sindy\sindy.jl:119
  SINDy(::AbstractArray{S,2}, !Matched::AbstractArray{S,1}, ::Basis, ::T; kwargs...) where {T<:DataDrivenDiffEq.Optimize.AbstractOptimizer, S<:Number} at C:\Users\Denis\.julia\packages\DataDrivenDiffEq\kSbz2\src\sindy\sindy.jl:124
  ...

Stacktrace:
 [1] kwerr(::NamedTuple{(:opt, :maxiter, :normalize, :denoise),Tuple{STRRidge{Int64},Int64,Bool,Bool}}, ::Function, ::Array{Float64,2}, ::LinearAlgebra.Adjoint{Float64,Array{Float64,1}}, ::Basis, ::STRRidge{Float64}) at .\error.jl:157
 [2] #SINDy#91 at C:\Users\Denis\.julia\packages\DataDrivenDiffEq\kSbz2\src\sindy\sindy.jl:125 [inlined]
 [3] top-level scope at .\In[14]:27
 [4] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091

**Comment by finmod** [comment]
Solved. The syntax error is : , opt = opt,  in the SINDy call. The current syntax is :  , opt, only. @RajDandekar, your files should read 

Ψ = SINDy(vcat(x_sol', y_sol'), UDE_SGLD[1:end], basis, opt, maxiter = 10000, normalize = true, denoise = true)

**Comment by ChrisRackauckas** [comment]
And it should get a project/manifest.

**Comment by RajDandekar** [comment]
@finmod Thanks for the suggestion..I have changed the syntax in the code

**Comment by ArnoStrouwen** [comment]
Small doc issue:
https://datadriven.sciml.ai/dev/sparse_identification/isindy/

\begin{align} \varphi{1} =& 1 \ \varphi{2} =& u \ \varphi{3} =& u^{2} \ \varphi{4} =& u^{3} \ \varphi{_5} =& u^{4} \end{align}

LaTeX seems to escape the output box of `basis= Basis([u^i for i in 0:4], [u])`
