### ISSUE TITLE
README example not updated for changes in Basis syntax 

### ISSUE THREAD

**Issue by finmod** [SciML/DataDrivenDiffEq.jl#181]
For:

@variables x y z
u = [x; y; z]
polys = Any[]
for i ∈ 0:4
    for j ∈ 0:i
        for k ∈ 0:j
            push!(polys, u[1]^i*u[2]^j*u[3]^k)
            push!(polys, u[2]^i*u[3]^j*u[1]^k)
            push!(polys, u[3]^i*u[1]^j*u[2]^k)
        end
    end
end

basis = Basis(polys, u)

opt = STRRidge(0.1)
Ψ = SINDy(X, DX, basis, opt, maxiter = 100, normalize = true)
print_equations(Ψ)
get_error(Ψ)

returns:

MethodError: no method matching Basis(::Array{Any,1}, ::Array{Operation,1})
Closest candidates are:
  Basis(::B, ::V, !Matched::P, !Matched::T, !Matched::Function) where {B, V, P, T} at C:\Users\Denis\.julia\packages\DataDrivenDiffEq\kn8bK\src\basis.jl:4
  Basis(!Matched::AbstractArray{Operation,N} where N, ::AbstractArray{Operation,N} where N; parameters, iv, eval_expression) at C:\Users\Denis\.julia\packages\DataDrivenDiffEq\kn8bK\src\basis.jl:68
  Basis(!Matched::Function, ::AbstractArray{Operation,N} where N; parameters, iv) at C:\Users\Denis\.julia\packages\DataDrivenDiffEq\kn8bK\src\basis.jl:95

Stacktrace:
 [1] top-level scope at In[8]:14
 [2] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091

**Comment by AlCap23** [comment]
I can not reproduce this. Running 

```julia

# Create a test problem
function lorenz(u,p,t)
    x, y, z = u
    ẋ = 10.0*(y - x)
    ẏ = x*(28.0-z) - y
    ż = x*y - (8/3)*z
    return [ẋ, ẏ, ż]
end

u0 = [-8.0; 7.0; 27.0]
p = [10.0; -10.0; 28.0; -1.0; -1.0; 1.0; -8/3]
tspan = (0.0,100.0)
dt = 0.001
problem = ODEProblem(lorenz,u0,tspan)
solution = solve(problem, Tsit5(), saveat = dt, atol = 1e-7, rtol = 1e-8)

X = Array(solution)
DX = similar(X)
for (i, xi) in enumerate(eachcol(X))
    DX[:,i] = lorenz(xi, [], 0.0)
end


@variables x y z
u = [x; y; z]
polys = Any[]
for i ∈ 0:4
    for j ∈ 0:i
        for k ∈ 0:j
            push!(polys, u[1]^i*u[2]^j*u[3]^k)
            push!(polys, u[2]^i*u[3]^j*u[1]^k)
            push!(polys, u[3]^i*u[1]^j*u[2]^k)
        end
    end
end

basis = Basis(polys, u)

opt = STRRidge(0.1)
Ψ = SINDy(X, DX, basis, opt, maxiter = 100, normalize = true)
print_equations(Ψ)
get_error(Ψ)
``` 
Gives exactly what I expect and no errors. Did you maybe use an earlier version here?

**Comment by finmod** [comment]
And I get that from running on julia 1.5.3 your code with:

using DataDrivenDiffEq, ModelingToolkit, OrdinaryDiffEq
using LinearAlgebra
using Plots; gr()

MethodError: no method matching Basis(::Array{Any,1}, ::Array{Operation,1})
Closest candidates are:
  Basis(::B, ::V, !Matched::P, !Matched::T, !Matched::Function) where {B, V, P, T} at C:\Users\Denis\.julia\packages\DataDrivenDiffEq\kn8bK\src\basis.jl:4
  Basis(!Matched::AbstractArray{Operation,N} where N, ::AbstractArray{Operation,N} where N; parameters, iv, eval_expression) at C:\Users\Denis\.julia\packages\DataDrivenDiffEq\kn8bK\src\basis.jl:68
  Basis(!Matched::Function, ::AbstractArray{Operation,N} where N; parameters, iv) at C:\Users\Denis\.julia\packages\DataDrivenDiffEq\kn8bK\src\basis.jl:95

Stacktrace:
 [1] top-level scope at In[5]:14
 [2] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091

**Comment by AlCap23** [comment]
Same version of julia here. But what about DataDriven / the output of `] st` ?

**Comment by finmod** [comment]
Status `C:\Users\Denis\.julia\environments\v1.5\Project.toml`
  [0bf59076] AdvancedHMC v0.2.27
  [c52e3926] Atom v0.12.30
  [6e4b80f9] BenchmarkTools v0.5.0
  [052768ef] CUDA v2.3.0
  [35d6a980] ColorSchemes v3.10.2
  [5ae59095] Colors v0.12.6
  [2445eb08] DataDrivenDiffEq v0.3.3
  [2b5f629d] DiffEqBase v6.44.3
  [aae7a2af] DiffEqFlux v1.24.0
  [41bf760c] DiffEqSensitivity v6.35.0
  [0c46a032] DifferentialEquations v6.16.0
  [31c24e10] Distributions v0.23.8
  [61744808] DynamicalSystems v1.4.0
  [6e36e845] DynamicalSystemsBase v1.5.7
  [53c48c17] FixedPointNumbers v0.8.4
  [587475ba] Flux v0.11.2
  [f6369f11] ForwardDiff v0.10.14
  [a2cc645c] GraphPlot v0.4.4
  [bd48cda9] GraphRecipes v0.5.4
  [7073ff75] IJulia v1.23.1
  [82e4d734] ImageIO v0.4.1
  [6218d12a] ImageMagick v1.1.6
  [4138dd39] JLD v0.12.0
  [033835bb] JLD2 v0.3.1
  [b964fa9f] LaTeXStrings v1.2.0
  [093fc24a] LightGraphs v1.3.4
  [97b447e0] MFGnet v0.1.0 `https://github.com/EmoryMLIP/MFGnet.jl#master`
  [961ee093] ModelingToolkit v3.20.1
  [315f7962] NeuralPDE v2.5.0
  [429524aa] Optim v1.2.1
  [1dea7af3] OrdinaryDiffEq v5.42.3
  [3b7a836e] PGFPlots v3.3.4
  [91a5bcdd] Plots v1.10.0
  [f27b6e38] Polynomials v1.2.0
  [438e738f] PyCall v1.92.1
  [d330b81b] PyPlot v2.9.0
  [1fd47b50] QuadGK v2.4.1
  [295af30f] Revise v3.1.11
  [47aef6b3] SimpleWeightedGraphs v1.1.1
  [2913bbd2] StatsBase v0.33.2
  [f3b207a7] StatsPlots v0.14.17
  [44eeaf0b] Vec v2.0.2 `https://github.com/sisl/Vec.jl.git#master`
  [44d3d7a6] Weave v0.10.6
  [e88e6eb3] Zygote v0.5.17
  [9e88b42a] Serialization

**Comment by AlCap23** [comment]
`[2445eb08] DataDrivenDiffEq v0.3.3` is before the update. Needs `>0.4` to work. Something is holding this back.

**Comment by finmod** [comment]
Correct. I do ] up constantly.

**Comment by AlCap23** [comment]
Try DiffEqBase, which is needed to be geq 6.45 . But this is my lucky guess here.

**Comment by finmod** [comment]
It does not make a difference. There is obviously a compatibility issue between all the packages.

**Comment by finmod** [comment]
Solved by setting up from scratch Julia 1.5.3 and the packages listed in DataDrivenDiffEq. It was obviously a compatibility problem somewhere in the SciML environment. 

It would be good to formulate the example in the README to show the capabilities of ModelingToolkit. This would fit nicely with PINNS examples in NeuralPDE and the potential interaction with DataDrivenDiffEq and others. Something like: 

using ModelingToolkit, Latexify

@parameters t σ ρ β
@variables x(t) y(t) z(t)
@derivatives D'~t

eqs = [D(x) ~ σ*(y-x),
       D(y) ~ x*(ρ-z)-y,
       D(z) ~ x*y - β*z]

lor = ODESystem(eqs)

latexify(lor)


There is this mystery(!) about the three original parameters becoming 7 parameters and what is really required as an input in DataDrivenDiffEq (currently 7 parameters). Also, the current output is non longer what is in the README. It is now:

 ##Basis#261 : 3 dimensional basis in ["x", "y", "z"]
Parameters : Sym{ModelingToolkit.Parameter{Real}}[p₁, p₂, p₃, p₄, p₅, p₆, p₇]

Independent variable: t
Equations
φ₁ = (p₁ * (((x ^ 1) * (y ^ 0)) * (z ^ 0))) + (p₂ * (((y ^ 1) * (z ^ 0)) * (x ^ 0)))
φ₂ = ((p₃ * (((x ^ 1) * (y ^ 0)) * (z ^ 0))) + (p₄ * (((y ^ 1) * (z ^ 0)) * (x ^ 0)))) + (p₅ * (((z ^ 1) * (x ^ 1)) * (y ^ 0)))
φ₃ = (p₆ * (((z ^ 1) * (x ^ 0)) * (y ^ 0))) + (p₇ * (((x ^ 1) * (y ^ 1)) * (z ^ 0)))
3-element Array{Float64,1}:
 8.62326288902255e-12
 3.505423292198665e-11
 1.496347116770034e-11

**Comment by ChrisRackauckas** [comment]
Wait, what makes you think it's a compatibility issue in the SciML repos? Which one? It sounds like if you only have the SciML repos you don't get the issue. Something like the lack of compat here:

https://github.com/sisl/Vec.jl/blob/master/Project.toml#L10-L13

is likely the culprit. Any dependency without CompatHelper is suspect, but all of our repos have compat tracking.

**Comment by AlCap23** [comment]
The seven parameters are not mysterious. We simply do not filter for approximately equal parameter values, which is a very special case - which would be of course optimal for our code. 

Right now, we simply assume that all are different, which is true in general. I had a discussion with Peter Crowe about this and maybe it will be an additional keyworded argument. Keep in mind that this will definitely influence the solution space of the model. Otherwise, you could always shrink down your own parameters using a function and reexport a new model. ( I will provide a minimal example later on ).

I think we are always biased in the use of those example cases. Trying to imagine me discovering the parameters of the model ( with noisy data ) I would rather assume that the nearly identical values are serendipity and ignore them at first. :wink:

**Comment by finmod** [comment]
This was just some fouled up registries and Project.TOMLs. I would not know where it started. The Julia reset is quick and effective.
