### ISSUE TITLE
UndefVarError <ₑ

### ISSUE THREAD

**Issue by korsbo** [SciML/DataDrivenDiffEq.jl#190]
Hello

I get an UndefVarError upon precompilation.

<ₑ is imported from ModelinToolkit at https://github.com/SciML/DataDrivenDiffEq.jl/blob/af22cdfd4d6b21a6c90e857da7202dcdb85863f6/src/basis.jl#L5
The version of MTK that I have (4.5.0) does not seem to have that defined. I don't really see <ₑ being used so maybe one could just remove the import that's causing grief. Otherwise, it might be a good idea to revise which MTK versions DataDrivenDiffEq is compatible with in Project.toml. 

Cheers!

**Comment by ChrisRackauckas** [comment]
I think when it was updated to v5 it's no longer compatible with v4 @shashi

**Comment by AlCap23** [comment]
Thanks! I'll push a quickfix after the tests are passing locally.
