### ISSUE TITLE
Model discovery from dataset with ContinuousDataDrivenProblem

### ISSUE THREAD

**Issue by finmod** [SciML/DataDrivenDiffEq.jl#219]
Nice work in the README example. Let me suggest that the printout of the discovered model should also print the values of the parameters at the same time as the discovered ODE system.

Also, I have already reduced successfully the length of the timeseries from dt  = 0.05 (10000 datapoints) to dt = 0.1 (1000 datapoints). It would be good to show a case of failure or a message of failure for 'ContinuousDataDrivenProblem' when the rank of the data matrix fails.

**Comment by AlCap23** [comment]
I will add a print of the `parameter_map(result)`. Since the system is a type of `ModelingToolkit.AbstractSystem` I don't know if we can directly store a set of initial parameters inside the struct.

**Comment by AlCap23** [comment]
I adapted the Readme.md copy past example accordingly. It's not the prettiest output, but its the printing we deserve.

Ah, I just saw I adapted everything else, but forgot to add the `print(ddsol, Val{true}`. Will close in a minute :smile:
