### ISSUE TITLE
Bug in Quickstart.md the cartpole example

### ISSUE THREAD

**Issue by finmod** [SciML/DataDrivenDiffEq.jl#223]
There is a bug in the cut and paste of the cartpole example from test to docs.

The basis formation should read:

implicits = [du;  du .* cos(u[1]);   du .* cos(u[1])^2; polys]

Excellent demo.

**Comment by AlCap23** [comment]
Thanks! I adapted the tests ( since the more basis functions, the merrier ;)) within #224
