### ISSUE TITLE
SparseRegressionProblem

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DataDrivenDiffEq.jl#226]
It would be good to expose a high level SparseRegressionProblem specifically for the sparse optimizers where `Y` is a required input, otherwise the `Y` is generated assuming it's a difference/derivative which is not what is wanted for all applications. Of course a user could use `sparse_regression!` directly, but it would be nice to have this hit the higher level API.

**Comment by AlCap23** [comment]
I'll add a `DirectDataDrivenProblem` where we can estimate the mappings X, p, t, U -> Y . 
This can, later on, be used for other techniques as well, e.g. symbolic regression or PCA.

**Comment by AlCap23** [comment]
Closed via #234
