### ISSUE TITLE
The nonlinear pendulum examples fails on `solve`

### ISSUE THREAD

**Issue by gzagatti** [SciML/DataDrivenDiffEq.jl#236]
I am trying to run the [example of the non-linear pendulum](https://datadriven.sciml.ai/dev/quickstart/#Nonlinear-Systems-Sparse-Identification-of-Nonlinear-Dynamics) by just copying and pasting but it fails in:

```julia
res = solve(prob, basis, opt, progress = false, denoise = false, normalize = false, maxiter = 5000)
````

with the following error:

```julia
ArgumentError: offset arrays are not supported but got an array with index other than 1
```

My current environment includes the following packages:

```julia
 [0c46a032] DifferentialEquations v6.17.2
 [961ee093] ModelingToolkit v5.21.0
 [1dea7af3] OrdinaryDiffEq v5.59.3
 [91a5bcdd] Plots v1.16.8
 [37e2e46d] LinearAlgebra
```

**Comment by AlCap23** [comment]
Encountered myself and fixed with #234  ;)

**Comment by gzagatti** [comment]
Nice, thanks!

**Comment by AlCap23** [comment]
Should be good to go, once v.0.6.3 is released ( just started the process, it might take some time ).
