### ISSUE TITLE
Docs Improvements

### ISSUE THREAD

**Issue by Gregliest** [SciML/DataDrivenDiffEq.jl#247]
Hi @AlCap23, I'm starting the process of learning about symbolic regression of neural networks, and @ChrisRackauckas suggested that I help improve the docs as I explore. I wanted to start this thread to capture anything that you think I should work on. 

I did a quick look through the docs and submitted a [PR](https://github.com/SciML/DataDrivenDiffEq.jl/pull/246) with basic fixes. 

In looking through the outstanding issues, it appears that there a few areas that could use improvement: 

- It looks like the "Getting Started" page should be reorganized: https://github.com/SciML/DataDrivenDiffEq.jl/issues/245. That will probably also address https://github.com/SciML/DataDrivenDiffEq.jl/issues/225. 

- It also sounds like the combining of SINDy and DMD methods needs to be described. I don't know that I have the background for that, but I'm happy to take a stab at it, especially with a little guidance. Also, how does this relate to symbolic regression, as in https://github.com/SciML/DataDrivenDiffEq.jl/issues/159? 

What else needs to be fixed or improved?

**Comment by AlCap23** [comment]
Hey and thank you very much! 

As mentioned in #245, I was mostly concerned with getting the API to run, resulting in a loss of information. A restructuring should also give the related papers, which I can add later on. 

Additionally, if you're interested in SR, the OccamNet could use some more examples and possible enhancements in the training of parameters. Feel free to send me a DM on Slack.

**Comment by Gregliest** [comment]
Ok great, do you have a list of those related papers you can send me?

**Comment by AlCap23** [comment]
I will compile one and put it into the docs folder, maybe using [DocumenterCitations](https://github.com/ali-ramadhan/DocumenterCitations.jl) is a good idea.
