### ISSUE TITLE
Enforcing rather old versions of Symbolics and ModelingToolkit

### ISSUE THREAD

**Issue by hurak** [SciML/DataDrivenDiffEq.jl#285]
I have noticed in Project.toml that DataDrivenDiffEq.jl enforces rather too conservative constraints on the versions of Symbolics.jl and ModelingToolkit.jl packages. They are both lagging by two and one version numbers, respectively. Is this intentional? 

I confess I still have not figured out how to live with all these version constraints imposed by individual packages in Julia and therefore this issue might be found irrelevant. Simply having just one major environment in which I keep all those common packages used for everyday work, I find it quite inconvenient to see major downgrades of important packages after installing DataDrivenDiffEq.jl.

**Comment by AlCap23** [comment]
There are some issues with the current Symbolics release and many of the functions used for handling the Basis, which I wasn't able to handle with some other things coming up during the last month. But I'll probably have a look today and see if I can adapt the combat bounds. 

That said, I totally agree with you on this and it has been bugging me a lot during the recent weeks.
