### ISSUE TITLE
Update of the  document "test/applications/partial_lotka_volterra.jl"

### ISSUE THREAD

**Issue by Song921012** [SciML/DataDrivenDiffEq.jl#286]
It seems that the document  "test/applications/partial_lotka_volterra.jl" is outdated and not compatible with version 0.6 now. Thank you!

**Comment by AlCap23** [comment]
Will do , but there is a working version [here](https://github.com/ChrisRackauckas/universal_differential_equations/blob/master/LotkaVolterra/scenario_1.jl).

This should also go into the docs.

**Comment by Song921012** [comment]
Ok, appreciate for your response
