### ISSUE TITLE
about version

### ISSUE THREAD

**Issue by liushang0322** [SciML/DataDrivenDiffEq.jl#308]
I just want to use Symbolics@4.1.0 and SymbolicUtils@0.18.0 in my pkg ,and I need DataDrivenDiffEq in my Pkg ,too.There is a version problem about SymbolicUtils and ModelingToolkit。
I need to use Symbolics@4.1.0 SymbolicUtils@0.18.0,ModelingToolkit will be update to 7.1.0,but DataDrivenDiffEq is Incompatible to these pkg，could you please solve such problems？
thank you so much

**Comment by ChrisRackauckas** [comment]
This hasn't been updated yet.

**Comment by AlCap23** [comment]
I'll fix the compat bounds to Symbolics >= 4 and MTK >= 7 and do a release if the checks are green within the hour.
