### ISSUE TITLE
is function for forward and backward DMD welcome as PR?

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/DataDrivenDiffEq.jl#313]
I have implemented the forward and backward DMD function (fbDMD). Is it okay to contribute as PR ? It is fbDMD without control. 
This version of DMD is said to be good for overcoming the noise effects in the literature
I have implemented it as directed in the appendix of the paper [Integrating multi-fidelity blood flow data with reduced-order data assimilation](https://www.sciencedirect.com/science/article/pii/S0010482521003607)
The implementation can be found here in the fork of DataDrivenDiffEq.jl at [here](https://github.com/yewalenikhil65/DataDrivenDiffEq.jl/blob/c94bce10ccb56d666ad6206a53a09e513e82cf44/src/koopman/algorithms.jl#L162)
I do not yet know how the tests in DataDrivenDiffEq.jl work so might need some help with the tests!

**Comment by AlCap23** [comment]
Awesome, that would be most welcome! Feel free to start a PR and we can then discuss the tests in the process.

I'll also have a look on how to integrate the control signal.

**Comment by yewalenikhil65** [comment]
> Awesome, that would be most welcome! Feel free to start a PR and we can then discuss the tests in the process.
> 
> I'll also have a look on how to integrate the control signal.

thanks, for now i have opened a [PR-314](https://github.com/SciML/DataDrivenDiffEq.jl/pull/314)

**Comment by yewalenikhil65** [comment]
https://github.com/SciML/DataDrivenDiffEq.jl/pull/337 seems this should be closed now
