### ISSUE TITLE
DataDrivenDiffEq dont work on 1.7.1

### ISSUE THREAD

**Issue by ecustwy** [SciML/DataDrivenDiffEq.jl#322]
when doing the Quick Demonstration on Julia1.7.1, the programm stoped at "ddprob = ContinuousDataDrivenProblem(sol)"
given: ERROR: UndefVarError: ContinuousDataDrivenProblem not defined
all the packages are up to date

**Comment by AlCap23** [comment]
Can you share a minimal working example of the code?

**Comment by AlCap23** [comment]
The current master runs for me without problems using `v1.7.1`. Can you try it on master?

**Comment by ChrisRackauckas** [comment]
Let's see: https://github.com/SciML/DataDrivenDiffEq.jl/pull/324

**Comment by AlCap23** [comment]
After the registration is done, should be good to go. ( #325 )

**Comment by ecustwy** [comment]
Thank you all, The problem has been sloved. 
I tried the up commond first, and then check the version. However it doesnt work, the version is stil the old one(0.5.7). Then I  removed the package and reinstll it from the git repo instead of “add DataDrivenDiffEq”. The console told me that the DataDrivenDiffEq was restricted by compatibility requirements with “BioMASS”(first try) and “DiffEqBayes”(Second try). (I didnot rember have seen these information before). I remove these two packages and the leatse version of DataDrivenDiffEq could be installed now.

[336ed68f] CSV v0.9.11
[052768ef] CUDA v3.6.3
[2445eb08] DataDrivenDiffEq v0.6.9 https://github.com/SciML/DataDrivenDiffEq.jl#master
[a93c6f00] DataFrames v1.3.1
[0c46a032] DifferentialEquations v7.0.0
[31c24e10] Distributions v0.25.37
[61744808] DynamicalSystems v2.1.5
[587475ba] Flux v0.12.8
