### ISSUE TITLE
ContinuousDataDrivenProblem

### ISSUE THREAD

**Issue by Mile124** [SciML/DataDrivenDiffEq.jl#336]
I'm running quick demonstration (julia Pro1.5.3), and the run shows: undefvarerror: continuousdatadrivenproblem not defined. Excuse me, how could I solve this problem.
![image](https://user-images.githubusercontent.com/101334942/158133420-e2c7f973-129d-412c-95f5-9a452b09b01a.png)

**Comment by AlCap23** [comment]
Whats the output of  ```] st```?

I would recommend to move away from JuliaPro, since its replaced by JuliaHub. Also a minimal version of 1.6.x :)

I strongly suspect that you are not using the current version of DataDrivenDifffEq.

**Comment by ChrisRackauckas** [comment]
Anything less than Julia v1.6 is not supported. In fact, JuliaPro has not been supported by JuliaComputing since 2020 anyways, so there's a lot messed up here. It's going to give you ancient package versions, etc. I would recommend just using a standard Julia installation from https://julialang.org/downloads/

**Comment by Mile124** [comment]
Thank you very much for your reply. As a newcomer who has just met Julia, it has reduced a lot of time for me




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SciML/DataDrivenDiffEq.jl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月14日(星期一) 晚上8:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SciML/DataDrivenDiffEq.jl] ContinuousDataDrivenProblem (Issue #336)





 
Anything less than Julia v1.6 is not supported. In fact, JuliaPro has not been supported by JuliaComputing since 2020 anyways, so there's a lot messed up here. It's going to give you ancient package versions, etc. I would recommend just using a standard Julia installation from https://julialang.org/downloads/
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
