### ISSUE TITLE
indirect dependency RegularizationTools has GPL license

### ISSUE THREAD

**Issue by johnnychen94** [SciML/DataDrivenDiffEq.jl#389]
DataDrivenDiffEq(MIT) <= DataInterpolations (MIT) <= RegularizationTools (GPL-3.0)

cc: @mdpetters

**Comment by AlCap23** [comment]
@ChrisRackauckas 

This should also be an issue in DataInterpolations.

**Comment by AlCap23** [comment]
I'll set a combat bound before the merger which did introduce RegularisationTools for now. 
This will be handled in DataInterpolations.

**Comment by AlCap23** [comment]
#390 https://github.com/PumasAI/DataInterpolations.jl/pull/128

**Comment by AlCap23** [comment]
Closed via #371
