### ISSUE TITLE
DiffEqFlux integration

### ISSUE THREAD

**Issue by AlCap23** [SciML/DataDrivenDiffEq.jl#54]
Right now, this works ( very slow ) 

```julia
using DiffEqFlux, OrdinaryDiffEq, Flux, Optim, Plots
using DataDrivenDiffEq, ModelingToolkit
using Zygote

u0 = Float32[2.; 0.]
datasize = 30
tspan = (0.0f0,1.5f0)

function trueODEfunc(du,u,p,t)
    true_A = [-0.1 2.0; -2.0 -0.1]
    du .= ((u.^3)'true_A)'
end
t = range(tspan[1],tspan[2],length=datasize)
prob = ODEProblem(trueODEfunc,u0,tspan)
ode_data = Array(solve(prob,Tsit5(),saveat=t))

@variables x[1:2]
# Lots of polynomials
polys = Operation[1]
for i ∈ 1:5
    push!(polys, x.^i...)
    for j ∈ 1:i-1
        push!(polys, x[1]^i*x[2]^j)
    end
end

# And some other stuff
h = [cos(x[1]); sin(x[1]); x[1]*x[2]; x[1]*sin(x[2]); x[2]*cos(x[2]); polys...]


basis = Basis(h, x)
gradient(x->sum(dudt2(x)), u0)

dudt2 = Chain(x->basis(x),Dense(length(basis), 2)) |> f32

n_ode = NeuralODE(dudt2,tspan,Tsit5(),saveat=t)

function predict_n_ode(p)
  n_ode(u0,p)
end

function loss_n_ode(p)
    pred = predict_n_ode(p)
    loss = sum(abs2,ode_data .- pred)
    loss,pred
end

loss_n_ode(n_ode.p) # n_ode.p stores the initial parameters of the neural ODE

cb = function (p,l,pred;doplot=false) #callback function to observe training
  display(l)
  # plot current prediction against data
  if doplot
    pl = scatter(t,ode_data[1,:],label="data")
    scatter!(pl,t,pred[1,:],label="prediction")
    display(plot(pl))
  end
  return false
end

# Display the ODE with the initial parameter values.
cb(n_ode.p,loss_n_ode(n_ode.p)...)

res1 = DiffEqFlux.sciml_train(loss_n_ode, n_ode.p, ADAM(0.01), cb = cb, maxiters = 100)
cb(res1.minimizer,loss_n_ode(res1.minimizer)...;doplot=true)
```

But fails for the optimizers from Optim.

**Comment by ChrisRackauckas** [comment]
```julia
using DiffEqFlux, OrdinaryDiffEq, Flux, Optim, Plots
using DataDrivenDiffEq, ModelingToolkit
using Zygote

u0 = Float32[2.; 0.]
datasize = 30
tspan = (0.0f0,1.5f0)

function trueODEfunc(du,u,p,t)
    true_A = [-0.1 2.0; -2.0 -0.1]
    du .= ((u.^3)'true_A)'
end
t = range(tspan[1],tspan[2],length=datasize)
prob = ODEProblem(trueODEfunc,u0,tspan)
ode_data = Array(solve(prob,Tsit5(),saveat=t))

@variables x[1:2]
# Lots of polynomials
polys = Operation[1]
for i ∈ 1:5
    push!(polys, x.^i...)
    for j ∈ 1:i-1
        push!(polys, x[1]^i*x[2]^j)
    end
end

# And some other stuff
h = [cos(x[1]); sin(x[1]); x[1]*x[2]; x[1]*sin(x[2]); x[2]*cos(x[2]); polys...]


basis = Basis(h, x)
dudt2 = FastChain(FastDense(2, length(basis)), (x,p)->basis(x),FastDense(length(basis), 2))
n_ode = NeuralODE(dudt2,tspan,Tsit5(),saveat=t)

function predict_n_ode(p)
  n_ode(u0,p)
end

function loss_n_ode(p)
    pred = predict_n_ode(p)
    loss = sum(abs2,ode_data .- pred)
    loss,pred
end

loss_n_ode(n_ode.p) # n_ode.p stores the initial parameters of the neural ODE

cb = function (p,l,pred;doplot=false) #callback function to observe training
  display(l)
  # plot current prediction against data
  if doplot
    pl = scatter(t,ode_data[1,:],label="data")
    scatter!(pl,t,pred[1,:],label="prediction")
    display(plot(pl))
  end
  return false
end

# Display the ODE with the initial parameter values.
cb(n_ode.p,loss_n_ode(n_ode.p)...)

res1 = DiffEqFlux.sciml_train(loss_n_ode, n_ode.p, ADAM(0.01), cb = cb, maxiters = 200)
res2 = DiffEqFlux.sciml_train(loss_n_ode, res1.minimizer, BFGS(), cb = cb, maxiters = 100)
cb(res1.minimizer,loss_n_ode(res2.minimizer)...;doplot=true)
```

this works and is fast, but the gradients are weird near the minimum... would you know why?

**Comment by AlCap23** [comment]
Nice! I did not get the FastChain to work. 

I didn't run this, buy maybe the constant part of the basis is the problem ( with the dense layers). I just blindly copy pasted it the first time around :)

**Comment by yewalenikhil65** [comment]
> ```julia
> using DiffEqFlux, OrdinaryDiffEq, Flux, Optim, Plots
> using DataDrivenDiffEq, ModelingToolkit
> using Zygote
> 
> u0 = Float32[2.; 0.]
> datasize = 30
> tspan = (0.0f0,1.5f0)
> 
> function trueODEfunc(du,u,p,t)
>     true_A = [-0.1 2.0; -2.0 -0.1]
>     du .= ((u.^3)'true_A)'
> end
> t = range(tspan[1],tspan[2],length=datasize)
> prob = ODEProblem(trueODEfunc,u0,tspan)
> ode_data = Array(solve(prob,Tsit5(),saveat=t))
> 
> @variables x[1:2]
> # Lots of polynomials
> polys = Operation[1]
> for i ∈ 1:5
>     push!(polys, x.^i...)
>     for j ∈ 1:i-1
>         push!(polys, x[1]^i*x[2]^j)
>     end
> end
> 
> # And some other stuff
> h = [cos(x[1]); sin(x[1]); x[1]*x[2]; x[1]*sin(x[2]); x[2]*cos(x[2]); polys...]
> 
> 
> basis = Basis(h, x)
> dudt2 = FastChain(FastDense(2, length(basis)), (x,p)->basis(x),FastDense(length(basis), 2))
> n_ode = NeuralODE(dudt2,tspan,Tsit5(),saveat=t)
> 
> function predict_n_ode(p)
>   n_ode(u0,p)
> end
> 
> function loss_n_ode(p)
>     pred = predict_n_ode(p)
>     loss = sum(abs2,ode_data .- pred)
>     loss,pred
> end
> 
> loss_n_ode(n_ode.p) # n_ode.p stores the initial parameters of the neural ODE
> 
> cb = function (p,l,pred;doplot=false) #callback function to observe training
>   display(l)
>   # plot current prediction against data
>   if doplot
>     pl = scatter(t,ode_data[1,:],label="data")
>     scatter!(pl,t,pred[1,:],label="prediction")
>     display(plot(pl))
>   end
>   return false
> end
> 
> # Display the ODE with the initial parameter values.
> cb(n_ode.p,loss_n_ode(n_ode.p)...)
> 
> res1 = DiffEqFlux.sciml_train(loss_n_ode, n_ode.p, ADAM(0.01), cb = cb, maxiters = 200)
> res2 = DiffEqFlux.sciml_train(loss_n_ode, res1.minimizer, BFGS(), cb = cb, maxiters = 100)
> cb(res1.minimizer,loss_n_ode(res2.minimizer)...;doplot=true)
> ```
> 
> this works and is fast, but the gradients are weird near the minimum... would you know why?

Hey @ChrisRackauckas , This example of using `basis` as layer seems to be not working now(mutating arrays error)..using GalacticOptim instead of `sciml_train`

Has anyone pursued this way of using `basis` functions as layer ..further ?

**Comment by AlCap23** [comment]
Hi!

Right now, this is the only working prototype I know of. And I haven't touched it for a while now.

That said, what are you aiming for? I think it should be possible to define the output function of a layer just as a function. If you're looking for a SINDy layer , you might want to look out for DiffOpt.jl which implements Convex Optimization into layers.

**Comment by yewalenikhil65** [comment]
> Hi!
> 
> Right now, this is the only working prototype I know of. And I haven't touched it for a while now.
> 
> That said, what are you aiming for? I think it should be possible to define the output function of a layer just as a function. If you're looking for a SINDy layer , you might want to look out for DiffOpt.jl which implements Convex Optimization into layers.

Well, i was looking for a alternate way to represent and learn chemical reactions .. and then stumbled upon `basis` layer discussion here..
eg. you can write most of chemical reactions in ODEs as,
` X' = netstoich_matrix * ode_rate_laws`
or for simple cases
`X' = netstoich_matrix * (polynomials_basis .* rate constants)`

We could do SINDy or other methods for simple cases, but for systems with multiscale systems , SINDy and many methods fail.

**Comment by yewalenikhil65** [comment]
> `X' = netstoich_matrix * (polynomials_basis .* rate constants)`
> so here parameters to learn that will completely describe the system will be ` netstoich_matrix` and `rate constants`
> 
You can imagine why i was tempted to see this discussion.. i hoped to write 
`NN = Chain((x,p)->basis(x), Dense(length(basis), 3,identity))`
and then pass it into neuralODE ..
its exactly like `X'= netstoich_matrix * (polynomials_basis .* rate constants)`..

**Comment by ChrisRackauckas** [comment]
What's the failure when you do that?

**Comment by yewalenikhil65** [comment]
> What's the failure when you do that?

cant claim i have tested for other examples.. but for this spiralODE problem itself, it leads to an `error of mutating arrays not allowed` after calling `GalacticOptim.solve()`..made me little doubtful about this
```julia
## copy pastign code from here.. before its data creation using spiralODE
@variables x[1:2]
basis = Basis(polynomial_basis(x,4),4);  # lots of polynomials
dudt2 = FastChain(FastDense(2, length(basis)), (x,p)->basis(x),FastDense(length(basis), 2))
n_ode = NeuralODE(dudt2,tspan,Tsit5(),saveat=t)

function predict_n_ode(p)
  n_ode(u0,p)
end

function loss_n_ode(p)
    pred = predict_n_ode(p)
    loss = sum(abs2,ode_data .- pred)
    loss,pred
end

loss_n_ode(n_ode.p) # n_ode.p stores the initial parameters of the neural ODE

cb = function (p,l,pred;doplot=false) #callback function to observe training
  display(l)
  # plot current prediction against data
  if doplot
    pl = scatter(t,ode_data[1,:],label="data")
    scatter!(pl,t,pred[1,:],label="prediction")
    display(plot(pl))
  end
  return false
end

# Display the ODE with the initial parameter values.
cb(n_ode.p,loss_n_ode(n_ode.p)...)    # leads to error

adtype = GalacticOptim.AutoZygote(); # or AutoForwardDiff
optf = GalacticOptim.OptimizationFunction((x, p) -> loss_n_ode(x), adtype)
optfunc = GalacticOptim.instantiate_function(optf, n_ode.p, adtype, nothing)
optprob = GalacticOptim.OptimizationProblem(optfunc, n_ode.p)
result_neuralode = GalacticOptim.solve(optprob, ADAM(0.05),cb = cb, maxiters = 300)
```

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DataDrivenDiffEq.jl/blob/master/src/basis.jl#L288-L298

Change that to:

```julia
function (b::Basis)(x::AbstractMatrix, p::AbstractArray = [], t::AbstractArray = [])
    isempty(t) ? nothing : @assert size(x, 2) == length(t)

    if (isempty(p) || eltype(p) <: Num) && !isempty(parameters(b))
        pi = isempty(p) ? parameters(b) : p
    else
        pi = p
    end

    map(1:size(x)[2]) do i
        res[:, i] .= b.f_(x[:, i], isempty(p) ? parameters(b) : p, isempty(t) ? zero(eltype(x)) : t[i])
    end
end
```

**Comment by yewalenikhil65** [comment]
> https://github.com/SciML/DataDrivenDiffEq.jl/blob/master/src/basis.jl#L288-L298
> 
> Change that to:
> 
> ```julia
> function (b::Basis)(x::AbstractMatrix, p::AbstractArray = [], t::AbstractArray = [])
>     isempty(t) ? nothing : @assert size(x, 2) == length(t)
> 
>     if (isempty(p) || eltype(p) <: Num) && !isempty(parameters(b))
>         pi = isempty(p) ? parameters(b) : p
>     else
>         pi = p
>     end
> 
>     map(1:size(x)[2]) do i
>         res[:, i] .= b.f_(x[:, i], isempty(p) ? parameters(b) : p, isempty(t) ? zero(eltype(x)) : t[i])
>     end
> end
> ```
Hi, i made these changes in my `..src/basis.jl` . But it creates same error.. 
```julia
Mutating arrays is not supported
error(::String) at error.jl:33
(::Zygote.var"#372#373")(::Nothing) at array.jl:58
(::Zygote.var"#2261#back#374"{Zygote.var"#372#373"})(::Nothing) at adjoint.jl:59
_create_array at code.jl:367 [inlined]
(::Zygote.var"#151#152"{typeof(∂(_create_array)),Tuple{Tuple{Nothing,Nothing,Nothing},NTuple{14,Nothing}}})(::Array{Float32,1}) at lib.jl:191
#1694#back at adjoint.jl:59 [inlined]
create_array at code.jl:378 [inlined]
macro expansion at code.jl:355 [inlined]
macro expansion at RuntimeGeneratedFunctions.jl:104 [inlined]
macro expansion at none:0 [inlined]
generated_callfunc at none:0 [inlined]
(::Zygote.var"#151#152"{typeof(∂(generated_callfunc)),Tuple{Tuple{Nothing},Tuple{Nothing,Nothing,Nothing}}})(::Array{Float32,1}) at lib.jl:191
(::Zygote.var"#1694#back#153"{Zygote.var"#151#152"{typeof(∂(generated_callfunc)),Tuple{Tuple{Nothing},Tuple{Nothing,Nothing,Nothing}}}})(::Array{Float32,1}) at adjoint.jl:59
RuntimeGeneratedFunction at RuntimeGeneratedFunctions.jl:92 [inlined]
(::typeof(∂(λ)))(::Array{Float32,1}) at interface2.jl:0
f_ at basis.jl:79 [inlined]
(::typeof(∂(λ)))(::Array{Float32,1}) at interface2.jl:0
Basis at basis.jl:282 [inlined]
(::typeof(∂(λ)))(::Array{Float32,1}) at interface2.jl:0
Basis at basis.jl:282 [inlined]
(::typeof(∂(λ)))(::Array{Float32,1}) at interface2.jl:0
#25 at some_trial.jl:24 [inlined]
(::typeof(∂(#25)))(::Array{Float32,1}) at interface2.jl:0
applychain at fast_layers.jl:20 [inlined]
(::typeof(∂(applychain)))(::SubArray{Float32,1,Array{Float32,1},Tuple{UnitRange{Int64}},true}) at interface2.jl:0
applychain at fast_layers.jl:20 [inlined]
(::typeof(∂(applychain)))(::SubArray{Float32,1,Array{Float32,1},Tuple{UnitRange{Int64}},true}) at interface2.jl:0
FastChain at fast_layers.jl:21 [inlined]
(::typeof(∂(λ)))(::SubArray{Float32,1,Array{Float32,1},Tuple{UnitRange{Int64}},true}) at interface2.jl:0
dudt_ at neural_de.jl:73 [inlined]
(::typeof(∂(λ)))(::SubArray{Float32,1,Array{Float32,1},Tuple{UnitRange{Int64}},true}) at interface2.jl:0
#327#back at adjoint.jl:59 [inlined]
#30 at derivative_wrappers.jl:290 [inlined]
(::typeof(∂(λ)))(::SubArray{Float32,1,Array{Float32,1},Tuple{UnitRange{Int64}},true}) at interface2.jl:0
(::Zygote.var"#41#42"{typeof(∂(λ))})(::SubArray{Float32,1,Array{Float32,1},Tuple{UnitRange{Int64}},true}) at interface.jl:40
_vecjacobian!(::SubArray{Float32,1,Array{Float32,1},Tuple{UnitRange{Int64}},true}, ::Array{Float32,1}, ::SubArray{Float32,1,Array{Float32,1},Tuple{UnitRange{Int64}},true}, ::Array{Float32,1}, ::Float32, ::DiffEqSensitivity.ODEInterpolatingAdjointSensitivityFunction{DiffEqSensitivity.AdjointDiffCache{Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Base.OneTo{Int64},UnitRange{Int64},LinearAlgebra.UniformScaling{Bool}},DiffEqSensitivity.InterpolatingAdjoint{0,true,Val{:central},DiffEqSensitivity.ZygoteVJP,Bool},Array{Float32,1},ODESolution{Float32,2,Array{Array{Float32,1},1},Nothing,Nothing,Array{Float32,1},Array{Array{Array{Float32,1},1},1},ODEProblem{Array{Float32,1},Tuple{Float32,Float32},false,Array{Float32,1},ODEFunction{false,DiffEqFlux.var"#dudt_#88"{NeuralODE{FastChain{Tuple{FastDense{typeof(identity),DiffEqFlux.var"#initial_params#73"{Array{Float32,1}}},var"#25#26",FastDense{typeof(identity),DiffEqFlux.var"#initial_params#73"{Array{Float32,1}}}}},Array{Float32,1},Nothing,Tuple{Float32,Float32},Tuple{Tsit5},Base.Iterators.Pairs{Symbol,StepRangeLen{Float32,Float64,Float64},Tuple{Symbol},NamedTuple{(:saveat,),Tuple{StepRangeLen{Float32,Float64,Float64}}}}}},LinearAlgebra.UniformScaling{Bool},Nothing,typeof(DiffEqFlux.basic_tgrad),Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,typeof(SciMLBase.DEFAULT_OBSERVED),Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},SciMLBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,DiffEqFlux.var"#dudt_#88"{NeuralODE{FastChain{Tuple{FastDense{typeof(identity),DiffEqFlux.var"#initial_params#73"{Array{Float32,1}}},var"#25#26",FastDense{typeof(identity),DiffEqFlux.var"#initial_params#73"{Array{Float32,1}}}}},Array{Float32,1},Nothing,Tuple{Float32,Float32},Tuple{Tsit5},Base.Iterators.Pairs{Symbol,StepRangeLen{Float32,Float64,Float64},Tuple{Symbol},NamedTuple{(:saveat,),Tuple{StepRangeLen{Float32,Float64,Float64}}}}}},LinearAlgebra.UniformScaling{Bool},Nothing,typeof(DiffEqFlux.basic_tgrad),Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,typeof(SciMLBase.DEFAULT_OBSERVED),Nothing},Array{Array{Float32,1},1},Array{Float32,1},Array{Array{Array{Float32,1},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float32,Float32}},DiffEqBase.DEStats},Nothing,ODEProblem{Array{Float32,1},Tuple{Float32,Float32},false,Array{Float32,1},ODEFunction{false,DiffEqFlux.var"#dudt_#88"{NeuralODE{FastChain{Tuple{FastDense{typeof(identity),DiffEqFlux.var"#initial_params#73"{Array{Float32,1}}},var"#25#26",FastDe...

```

**Comment by yewalenikhil65** [comment]
This is same example using `Chain` instead of `FastChain`.. and including only x1.^3 and x2.^3 polynomial terms that matter..for cheating purpose.. This results in method error while evaluating loss function itself.
```julia
ERROR: MethodError: no method matching (::var"#60#61")(::Array{Float32,1})
```
code as
```julia
@variables x[1:2]
basis = Basis(x.^3,x);  # 
dudt2 = Chain((x,p)->basis(x), Dense(length(basis), 50,tanh),Dense(50,2))
# this should be same as Chain(x -> x.^3, Dense(2, 50,tanh),Dense(50,2)).
p,re = Flux.destructure(dudt2) # use this p as the initial condition!
dudt(u,p,t) = re(p)(u) # need to restrcture for backprop!
prob = ODEProblem(dudt,u0,tspan)

function predict_n_ode()
  Array(solve(prob,Tsit5(),u0=u0,p=p,saveat=t))
end
function loss_n_ode()
    pred = predict_n_ode()
    loss = sum(abs2,ode_data .- pred)
    loss
end
loss_n_ode()

```

**Comment by AlCap23** [comment]
The changes by @ChrisRackauckas remove the mutation by not preallocating the array `res`. I think I got carried by aiming for speed some time ago and introduced this without thinking about the implications.

I will do a local check and push it, also change it in the PR #201 .

**Comment by yewalenikhil65** [comment]
> The changes by @ChrisRackauckas remove the mutation by not preallocating the array `res`. I think I got carried by aiming for speed some time ago and introduced this without thinking about the implications.
> 
> I will do a local check and push it, also change it in the PR #201 
after making suggested changes, i still ran into errors at
https://github.com/SciML/DataDrivenDiffEq.jl/blob/master/src/basis.jl#L282
and
https://github.com/SciML/DataDrivenDiffEq.jl/blob/master/src/basis.jl#L79

these too need any changes ?

**Comment by ChrisRackauckas** [comment]
Mutation only helps speed by not creating the array. Since the function creates the array, it might as well fill it at the same time with no speed loss.

**Comment by AlCap23** [comment]
I'll have a more detailed look into it right now. 

If you checkout DataDriven with the `iip_fix` branch via 
```julia
] add DataDrivenDiffEq #iip_fix
``` 
Do you get the same error? The tests are green on my machine.

**Comment by yewalenikhil65** [comment]
> I'll have a more detailed look into it right now.
> 
> If you checkout DataDriven with the `iip_fix` branch via
> 
> ```julia
> ] add DataDrivenDiffEq #iip_fix
> ```
> 
> Do you get the same error? The tests are green on my machine.

updated to `DataDrivenDiffEq v0.5.7 `https://github.com/SciML/DataDrivenDiffEq.jl.git#iip_fix`` 
Gives same error.

**Comment by AlCap23** [comment]
```julia
using ModelingToolkit
using DiffEqFlux
using DataDrivenDiffEq
using GalacticOptim
using OrdinaryDiffEq

u0 = Float32[2.; 0.]
datasize = 30
tspan = (0.0f0,1.5f0)

function trueODEfunc(du,u,p,t)
    true_A = [-0.1 2.0; -2.0 -0.1]
    du .= ((u.^3)'true_A)'
end
t = range(tspan[1],tspan[2],length=datasize)
prob = ODEProblem(trueODEfunc,u0,tspan)
ode_data = Array(solve(prob,Tsit5(),saveat=t))

## copy pastign code from here.. before its data creation using spiralODE
@variables x[1:2]
polys = polynomial_basis(x,4)
f_oop = build_function(polys, x, expression = Val{false})[1]
f_layer(x,p) = f_oop(x)
dudt_ = FastChain(FastDense(2, length(polys)), f_layer ,FastDense(length(polys), 2))
n_ode = NeuralODE(dudt_,tspan,Tsit5(),saveat=t)
ps = deepcopy(n_ode.p)
function predict_n_ode(p)
  Array(n_ode(u0,p))
end

function loss_n_ode(p)
    pred = predict_n_ode(p)
    loss = sum(abs2,ode_data .- pred)
    loss,pred
end

loss_n_ode(n_ode.p) # n_ode.p stores the initial parameters of the neural ODE

cb = function (p,l,pred;doplot=false) #callback function to observe training
  display(l)
  # plot current prediction against data
  if doplot
    pl = Plots.scatter(t,ode_data[1,:],label="data")
    Plots.scatter!(pl,t,pred[1,:],label="prediction")
    display(plot(pl))
  end
  return false
end

# Display the ODE with the initial parameter values.
cb(n_ode.p,loss_n_ode(n_ode.p)...)    # leads to error

res = DiffEqFlux.sciml_train(loss_n_ode, ps, ADAM(), maxiters = 10)
```

I was able to reproduce the error. Note that no `Basis` is involved. This seems to be something different.

**Comment by ChrisRackauckas** [comment]
@shashi did you make `build_function` for out of place mutating? It shouldn't be mutating.

**Comment by yewalenikhil65** [comment]
>I was able to reproduce the error. Note that no Basis is involved. This seems to be something different.
>
Weird.. I still get the same error.
![image](https://user-images.githubusercontent.com/26343789/111025639-6b9ead80-840b-11eb-850d-fc40ef7ee4c0.png)

**Comment by AlCap23** [comment]
Yes. This seems to be something different. 
The bug in DataDriven is also valid but seems not to be the cause of this.

**Comment by shashi** [comment]
https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/master/src/code.jl#L363-L370 it's here.... So we use this to construct vectors (but not matrices), I can fix this. But I think we will need the new concat syntax do this properly for dims >= 3.

**Comment by yewalenikhil65** [comment]
> ```julia
> using ModelingToolkit
> using DiffEqFlux
> using DataDrivenDiffEq
> using GalacticOptim
> using OrdinaryDiffEq
> 
> u0 = Float32[2.; 0.]
> datasize = 30
> tspan = (0.0f0,1.5f0)
> 
> function trueODEfunc(du,u,p,t)
>     true_A = [-0.1 2.0; -2.0 -0.1]
>     du .= ((u.^3)'true_A)'
> end
> t = range(tspan[1],tspan[2],length=datasize)
> prob = ODEProblem(trueODEfunc,u0,tspan)
> ode_data = Array(solve(prob,Tsit5(),saveat=t))
> 
> ## copy pastign code from here.. before its data creation using spiralODE
> @variables x[1:2]
> polys = polynomial_basis(x,4)
> f_oop = build_function(polys, x, expression = Val{false})[1]
> f_layer(x,p) = f_oop(x)
> dudt_ = FastChain(FastDense(2, length(polys)), f_layer ,FastDense(length(polys), 2))
> n_ode = NeuralODE(dudt_,tspan,Tsit5(),saveat=t)
> ps = deepcopy(n_ode.p)
> function predict_n_ode(p)
>   Array(n_ode(u0,p))
> end
> 
> function loss_n_ode(p)
>     pred = predict_n_ode(p)
>     loss = sum(abs2,ode_data .- pred)
>     loss,pred
> end
> 
> loss_n_ode(n_ode.p) # n_ode.p stores the initial parameters of the neural ODE
> 
> cb = function (p,l,pred;doplot=false) #callback function to observe training
>   display(l)
>   # plot current prediction against data
>   if doplot
>     pl = Plots.scatter(t,ode_data[1,:],label="data")
>     Plots.scatter!(pl,t,pred[1,:],label="prediction")
>     display(plot(pl))
>   end
>   return false
> end
> 
> # Display the ODE with the initial parameter values.
> cb(n_ode.p,loss_n_ode(n_ode.p)...)    # leads to error
> 
> res = DiffEqFlux.sciml_train(loss_n_ode, ps, ADAM(), maxiters = 10)
> ```
> 
> I was able to reproduce the error. Note that no `Basis` is involved. This seems to be something different.

@AlCap23  This does work now after updates in Symbolics.. shall we close this ?
