### ISSUE TITLE
Linear evolution of NonlinearKoopman

### ISSUE THREAD

**Issue by agerlach** [SciML/DataDrivenDiffEq.jl#97]
I recently needed to extract the underlying system from a `gEDMD` call to use in some other code and as a sanity check I wanted to compare a numerical ODE solve to C*exp(At) for the resulting EDMD solution. These are not matching and I believe that they should. However, I may be miss understanding what `NonlinearKoopman` structs are meant to represent. It looks to me that NonlinearKoopman represents the a finite linear approximation of the Koopman Operator on the lifted spaced defined by the basis given. However, you define the ODE as
```julia
function (k::NonlinearKoopman)(u,  p::AbstractArray = [], t = nothing)
    return k.output*k.operator*k.basis(u, p, t)
end
```
This is in general a non-linear system of equations due to k.basis(u,p,t). This is effectively enforcing consistency between the original states and the observables during evolution. This has practical benefits, but seems to no longer treat Koopman in a linear setting. Am I missing something here?

Thanks

Here is a MWE:

```
using DataDrivenDiffEq
using ModelingToolkit
using OrdinaryDiffEq
using LinearAlgebra
using Plots; gr()

# Define variables and basis functions
@variables u[1:2]
h = [u[1], u[2], sin(u[1]), cos(u[1]), sin(u[2]), cos(u[2]), sin(u[1])^3*cos(u[2]), sin(u[2])^3*cos(u[1]), cos(u[1])^3*sin(u[2]),cos(u[2])^3*sin(u[1])]

# Create internal basis representation
basis = Basis(h, u)

# Define System of interest
function vanderpol(du,u,p,t)
    μ = p[1]
    du[1] = u[2]
    du[2] = μ*(1.0-u[1]^2)*u[2] - u[1]
end

# Define simulation setup for Extended DMD
params = [0.5,]
u0 = [3.0, 2.0]
tspan = (0.0, 10.0)

# Setup and solve diffEQ
prob = ODEProblem(vanderpol, u0, tspan, params)
sol = solve(prob, Tsit5())

# Extract state and derivative information from simulation
X = sol[:,:]
DX = sol(sol.t, Val{1})[:,:]

# Run Extended DMD to approximate Linear operator on the basis given.
λ = 0.0 
approximator = gEDMD(X, DX, basis, alg = DMDSVD(λ))

# Simulate high dimensional ?linear? system
prob_approx = ODEProblem(approximator, u0, tspan)
sol_approx = solve(prob_approx, Tsit5())

# Solve as C*exp(At)
A = approximator.operator
C = approximator.output
lifted = basis(u0)

t_disc = range(tspan[1], tspan[2]*.5, length=100)
sol_expA = [C*exp(A*t_)*lifted for t_ ∈ t_disc]

begin
    plot(sol, vars = (1,2), label = "truth")
    plot!(sol_approx, vars = (1,2), label="linear")
    plot!(getindex.(sol_expA,1), getindex.(sol_expA,2), label="exp(At)")
end
```

**Comment by AlCap23** [comment]
You are right in the sense that we let go of the linearity for practical reasons. The `NonlinearKoopman`is right now a placeholder for a Koopman Operator which is, opposed to DMD, lifted to a nonlinear observeable and has certain features ( outputmap etc. ).

The reference for `gEDMD` can be found [here](https://arxiv.org/pdf/1909.10638.pdf), in which also the bridge from differential observeables to differential states is mentioned ( and its connection to SINDy ).

I think you are trying to use the map `C` , which maps the tangent space of the koopman observeable onto the tangent space of the states to map the observeables onto the states.
While this is a linear map at the derivative level , it might not be in the states.

I have used the slow manifold system from the reference since it has a finite koopman space associated with it.

```julia

using OrdinaryDiffEq
using Plots
gr()

using DataDrivenDiffEq
using LinearAlgebra
using ModelingToolkit

@variables u[1:2]

observeables = [u; u[1]^2]

basis = Basis(observeables, u)

function slow_manifold(du, u, p, t)
  du[1] = p[1]*u[1]
  du[2] = p[2]*(u[2]-u[1]^2)
end

u0 = [3.0; -2.0]
tspan = (0.0, 10.0)
p = [-0.05, -0.9]

problem = ODEProblem(slow_manifold, u0, tspan, p)
solution = solve(problem, Tsit5(), saveat = 0.2)

plot(solution)

X = Array(solution)
# This enforces more accurate results
DX = similar(X)
for (i,dx) in enumerate(eachcol(DX))
    slow_manifold(dx, X[:, i], p, solution.t[i])
end

# Run Extended DMD to approximate Linear operator on the basis given.
λ = 0.0
approximator = gEDMD(X, DX, basis, alg = DMDSVD(λ))

# Simulate high dimensional ?linear? system
prob_approx = ODEProblem(approximator, u0, tspan)
sol_approx = solve(prob_approx, Tsit5())
plot!(sol_approx)
# Solve as C*exp(At)
A = generator(approximator)
C = outputmap(approximator)
# Approximate the derivatives
DX_ = A*basis(X[:, 1:end-1])
plot(DX')
plot(DX_')

# Approximate state mapping
sol_expA = hcat([exp(A*t_)*basis(u0) for t_ ∈ solution.t])
plot((C*sol_expA)')
plot!(X')

# Linear Approximation of Koopman
Â = C*A*pinv(C)
sol_expA = hcat([exp(Â*t_)*basis(u0) for t_ ∈ solution.t])
plot((C*sol_expA)')
plot!(X')

``` 

If you want to have the proper mapping you have to compute it from the solutions.

Also, do you know that the finite approxiation of the vanderpol is correct ? It is unstable in your case. This could also be a problem ( plus numerics, as always ).

**Comment by agerlach** [comment]
Thanks. I think the slow manifold example highlights the problem. I don't think the resulting generator is correct and the way you are simulating the approximator is covering the problem up. 

Following the Carleman linearization approach in [Brunton](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4769143/pdf/pone.0150171.pdf) leads to 

```julia
A_brunton = [p[1] 0 0; 0 p[2] -p[2]; 0 0 2p[1]]
```

however the output of `gEDMD` is as follows (note difference in last element)

```julia
A_gEDMD = [p[1] 0 0; 0 p[2] -p[2]; 0 0 p[1]^2]
```

using `C*exp(A_brunton*t)* basis(u0)` produces the correct response. 

So, why does solving numerically with your `NonlinearKoopman` operator work? Effectively for your ODE you have 

```julia
[1 0 0; 0 1 0] * [p[1] 0 0; 0 p[2] -p[2]; 0 0 p[1]^2] * [u1; u2; u1^2]
```

To be explicit, here u1^2 is NOT a lifted state, but is a non-linear operation. If you work through the matrix multiplication you end up with 

```julia
[p[1]*u1; p[2]*(u2-u1^2)]
```
which is the original EOM. So, in some sense the system ID worked despite the incorrect generator b/c the output map drops the last state. I doubt it will work out this way in general. Especially in cases where the basis doesn't span the linear invariant sub-space.

**Comment by AlCap23** [comment]
Ah, okay. This is a problem. But I think I can fix this.

Thank you! I got you really with the slow manifold right now. The sines were a little bit to much :)

**Comment by AlCap23** [comment]
Okay, just running the tests locally and then pushing.

I have forgotten to use d/dt(Basis) instead of Basis. So we calculated the wrong stuff here. 
The outputmap is working fine. 

Thanks for the issue! :+1:

**Comment by agerlach** [comment]
My original MWE wasn't so minimal. I didn't even realize the problem until I looked at the slow manifold system. Thanks for your help. Teamwork FTW!

I'm confused by your comment about the outputmap though. I will admit that I have not read the gEDMD paper, so maybe this nuance of that vs. EDMD. The outputmap looks fine in the example. B/c the original states are in the basis it should just be selecting the appropriate rows in the basis vector, which it is in these examples. 

I do question the correctness of doing the following due to the non-linearities. This is not evolving the system via the Koopman Operator.
```
function (k::NonlinearKoopman)(u,  p::AbstractArray = [], t = nothing)
    return k.output*k.operator*k.basis(u, p, t)
end
```
Does this show up in the literature? I have not seen it, but that doesn't mean much since this area is moving so fast.

**Comment by AlCap23** [comment]
In the paper they connect gEDMD to SINDy as a special case. So you can think of the `C*K` as the sparse coefficients of the sindy estimation. 

So what we are doing is not really use the koopman stuff ( right now, but we can !)  for the simulation, but the nonlinear system rep.

**Comment by AlCap23** [comment]
I'll close this now ( should be fixed via accidentally pushing to master  in 2e4851d )

**Comment by AlCap23** [comment]
Feel free to reach out via Slack or mail to continue the discussion :)

**Comment by agerlach** [comment]
> you can think of the C*K as the sparse coefficients of the sindy estimation
Ah! That makes sense. Thanks for taking the time to explain. Keep up the awesome work.
