### ISSUE TITLE
Link to documentation in README is brocken

### ISSUE THREAD

**Issue by freemin7** [SciML/DataDrivenDiffEq.jl#99]
This link no longer works:
http://docs.juliadiffeq.org/dev/analysis/structural_estimation.html

**Comment by AlCap23** [comment]
Never did :).

You can find a draft at

https://datadriven.sciml.ai/dev/

**Comment by freemin7** [comment]
The stable link is still broken

**Comment by AlCap23** [comment]
Right now we only have the Dev docs. But hopefully stable will follow soon. ;)

**Comment by ChrisRackauckas** [comment]
A release needs to be made and then the stable docs will be available.
